### ISSUE TITLE
Can the NtWriteFile function be written to a partitioned device in use?

### ISSUE THREAD

**Issue by O1d-King** [hillu/go-ntdll#21]
When I use NTDLL to read from a disk and write to another disk, I can only delete the volume of the target device before I can write to it.
otherwise I will get the following message:

ntdll.status : STATUS_ACCESS_DENIED
317 0 The operation completed successfully.
2023-03-14 15:21:45 [Error]  NtWriteFile Error: 3221225506, error2:3
2023-03-14 15:21:45 [Error]  Write Data fail. error: Write Error

I am not sure if there is a way around this restriction to write data to a normal device that is in use without first deleting the volume.
Thanks

**Comment by hillu** [comment]
I have no experience with writing to block devices on Windows, so I don't know about any internal locking taking place. This does not seem to be a `go-ntdll`-specific problem.

**Comment by hillu** [comment]
@O1d-King have you been able to find the cause of your problem?

**Comment by hillu** [comment]
@O1d-King ping?

**Comment by hillu** [comment]
closing after a year of inactivity
