### ISSUE TITLE
anyarray length should not be generated to [1]ARRAYTYPE

### ISSUE THREAD

**Issue by maxifom** [hillu/go-ntdll#22]
Example:
ntdll.NtAdjustPrivilegesToken it has got anyarray in c, which is 1. But golang does not allow [1]array to contain more than 1 element, and the function does not work.

**Comment by maxifom** [comment]
https://stackoverflow.com/questions/9195889/what-is-the-purpose-of-anysize-array-in-winnt-h

**Comment by maxifom** [comment]
I solved it with 2 calls to functions for 2 proveleges, but its a case for changes in generation logic i guess

**Comment by hillu** [comment]
Unfortunately, there does not be good generic way to do this. Increasing the value would break code that allocates such structs.

But it might be possible to add helper functions to the types that contain those arrays.

**Comment by hillu** [comment]
@maxifom I just added code to generate helper methods for these structs, assuming that it alleviates your problem. Please tell me if this does what you need.

**Comment by maxifom** [comment]
Yeah, that works. Thanks!

**Comment by hillu** [comment]
@maxifom I have now added a more generalized version and also implemented setters. Thanks for the inspiration. :-)
